// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	entity "delayed-notifier/internal/entity"
)

// NotifyProducer is an autogenerated mock type for the NotifyProducer type
type NotifyProducer struct {
	mock.Mock
}

type NotifyProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *NotifyProducer) EXPECT() *NotifyProducer_Expecter {
	return &NotifyProducer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, notify
func (_m *NotifyProducer) Send(ctx context.Context, notify entity.Notify) error {
	ret := _m.Called(ctx, notify)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Notify) error); ok {
		r0 = rf(ctx, notify)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotifyProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type NotifyProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - notify entity.Notify
func (_e *NotifyProducer_Expecter) Send(ctx interface{}, notify interface{}) *NotifyProducer_Send_Call {
	return &NotifyProducer_Send_Call{Call: _e.mock.On("Send", ctx, notify)}
}

func (_c *NotifyProducer_Send_Call) Run(run func(ctx context.Context, notify entity.Notify)) *NotifyProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Notify))
	})
	return _c
}

func (_c *NotifyProducer_Send_Call) Return(_a0 error) *NotifyProducer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NotifyProducer_Send_Call) RunAndReturn(run func(context.Context, entity.Notify) error) *NotifyProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotifyProducer creates a new instance of NotifyProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotifyProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotifyProducer {
	mock := &NotifyProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
